version: &version 2.1


####################
# Templates
####################

executors:
  scala_212:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.12.14
  scala_213:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.13.6

commands:
  build:
    parameters:
      build-steps:
        description: "build steps"
        type: steps
        default: []
    steps:
      - checkout
      - run:
          command: |
            sbt clean "project $TEST_PROJECT" scalastyle test:scalastyle test


####################
# Jobs
####################

jobs:
  avro_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzur-avro
    steps:
      - build
  core_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzur-core
    steps:
      - build
  examples_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzur-examples
    steps:
      - build
  schemas_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzur-schemas
    steps:
      - build
  scio_212:
    executor: scala_212
    environment:
      TEST_PROJECT=elitzur-scio
    steps:
      - build
      
  avro_213:
    executor: scala_213
    environment:
      TEST_PROJECT=elitzur-avro
    steps:
      - build
  core_213:
    executor: scala_213
    environment:
      TEST_PROJECT=elitzur-core
    steps:
      - build
  examples_213:
    executor: scala_213
    environment:
      TEST_PROJECT=elitzur-examples
    steps:
      - build
  schemas_213:
    executor: scala_213
    environment:
      TEST_PROJECT=elitzur-schemas
    steps:
      - build
  scio_213:
    executor: scala_213
    environment:
      TEST_PROJECT=elitzur-scio
    steps:
      - build


####################
# Workflows
####################

workflows:
  version: *version

  # Per commit build
  build:
    jobs:
      - avro_212
      - core_212
      - examples_212
      - schemas_212
      - scio_212

      - avro_213
      - core_213
      - examples_213
      - schemas_213
      - scio_213
